lavender: qcom-caf --> oss-hals that would be better
* FAILED: analyzing Android.bp files and generating ninja file at /mnt/rizkyfebian/test/out/soong/build.ninja
Outputs: /mnt/rizkyfebian/test/out/soong/build.ninja
Error: exited with code: 1
Command: cd "$(dirname "/mnt/rizkyfebian/test/out/host/linux-x86/bin/soong_build")" && BUILDER="$PWD/$(basename "/mnt/rizkyfebian/test/out/host/linux-x86/bin/soong_build")" && cd / && env -i  "$BUILDER"     --top "$TOP"     --soong_out "/mnt/rizkyfebian/test/out/soong"     --out "/mnt/rizkyfebian/test/out"     -o /mnt/rizkyfebian/test/out/soong/build.ninja --globListDir build --globFile /mnt/rizkyfebian/test/out/soong/globs-build.ninja -t -l /mnt/rizkyfebian/test/out/.module_paths/Android.bp.list --available_env /mnt/rizkyfebian/test/out/soong/soong.environment.available --used_env /mnt/rizkyfebian/test/out/soong/soong.environment.used.build Android.bp
Output:
[31merror:[0m frameworks/native/services/surfaceflinger/Android.bp:246:1: "surfaceflinger" depends on undefined module "//device/xiaomi/lavender/qcom-caf/display:display_intf_headers"
[31merror:[0m frameworks/native/services/surfaceflinger/fuzzer/Android.bp:81:1: "surfaceflinger_fuzzer" depends on undefined module "//device/xiaomi/lavender/qcom-caf/display:display_intf_headers"
[31merror:[0m frameworks/native/services/surfaceflinger/fuzzer/Android.bp:115:1: "surfaceflinger_layer_fuzzer" depends on undefined module "//device/xiaomi/lavender/qcom-caf/display:display_intf_headers"
[31merror:[0m frameworks/native/services/surfaceflinger/fuzzer/Android.bp:105:1: "surfaceflinger_scheduler_fuzzer" depends on undefined module "//device/xiaomi/lavender/qcom-caf/display:display_intf_headers"
[31merror:[0m frameworks/native/services/surfaceflinger/fuzzer/Android.bp:91:1: "surfaceflinger_displayhardware_fuzzer" depends on undefined module "//device/xiaomi/lavender/qcom-caf/display:display_intf_headers"

Signed-off-by: FebriCahyaa <febricahya12345@gmail.com>