lavender: Resolve conflict in power-libperfmgr definitions
This commit addresses a conflict in power-libperfmgr definitions, specifically with the target android.hardware.power-service.xiaomi-libperfmgr. There was a clash between the definitions in hardware/xiaomi/aidl/power-libperfmgr/Android.mk and device/xiaomi/lavender/staging/power-libperfmgr/Android.mk.

To resolve this issue, the target in the staging directory has been modified to android.hardware.power-service.lavender-libperfmgr-staging, ensuring a distinct name to avoid conflicts. Please review the changes made in the staging directory to prevent any unintended disruptions.

This adjustment aims to maintain a clean build environment and prevent any ambiguity in target definitions.

Bug:
FAILED: including hardware/xiaomi/Android.mk ...
Error: makefile error
Output:
In file included from hardware/synaptics/wlan/synadhd/Android.mk:1:
In file included from hardware/xiaomi/Android.mk:19:
In file included from hardware/xiaomi/aidl/Android.mk:17:
In file included from hardware/xiaomi/aidl/power-libperfmgr/Android.mk:63:
In file included from build/make/core/executable.mk:53:
In file included from build/make/core/executable_internal.mk:29:
In file included from build/make/core/dynamic_binary.mk:34:
In file included from build/make/core/binary.mk:9:
[1mbuild/make/core/base_rules.mk:338: [31merror: [0m[1mhardware/xiaomi/aidl/power-libperfmgr: MODULE.TARGET.EXECUTABLES.android.hardware.power-service.xiaomi-libperfmgr already defined by device/xiaomi/lavender/staging/power-libperfmgr.[0m

Signed-off-by: FebriCahyaa <febricahya12345@gmail.com>